from __future__ import annotations

from typing import Any

ORGANIZATIONS: list[dict[str, Any]] = [
    {
        "id": "org_demo_buyer",
        "slug": "demo-buyer",
        "name": "开工吧演示企业",
        "owner_user_id": "user_demo",
    },
    {
        "id": "org_kaigongba",
        "slug": "kaigongba",
        "name": "开工吧官方",
        "owner_user_id": "admin",
    },
    {
        "id": "org_legal_planet",
        "slug": "legal-planet",
        "name": "法务星球工作室",
        "owner_user_id": "provider_user_legal_planet",
    },
    {
        "id": "org_shujian",
        "slug": "shujian",
        "name": "数见智能",
        "owner_user_id": "provider_user_shujian",
    },
    {
        "id": "org_talent_engine",
        "slug": "talent-engine",
        "name": "人才引擎",
        "owner_user_id": "provider_user_talent_engine",
    },
    {
        "id": "org_youfu",
        "slug": "youfu",
        "name": "优服智能",
        "owner_user_id": "user_demo",
    },
    {
        "id": "org_biaoxing",
        "slug": "biaoxing",
        "name": "标兴咨询",
        "owner_user_id": "provider_user_biaoxing",
    },
    {
        "id": "org_cloud_ops",
        "slug": "cloud-ops",
        "name": "云维科技",
        "owner_user_id": "user_demo",
    },
    {
        "id": "org_far_mirror",
        "slug": "far-mirror",
        "name": "远镜研究社",
        "owner_user_id": "provider_user_far_mirror",
    },
]


PROVIDERS: list[dict[str, str]] = [
    {"id": "provider_kaigongba", "organization_id": "org_kaigongba", "slug": "kaigongba"},
    {
        "id": "provider_legal_planet",
        "organization_id": "org_legal_planet",
        "slug": "legal-planet",
    },
    {"id": "provider_shujian", "organization_id": "org_shujian", "slug": "shujian"},
    {
        "id": "provider_talent_engine",
        "organization_id": "org_talent_engine",
        "slug": "talent-engine",
    },
    {"id": "provider_youfu", "organization_id": "org_youfu", "slug": "youfu"},
    {"id": "provider_biaoxing", "organization_id": "org_biaoxing", "slug": "biaoxing"},
    {"id": "provider_cloud_ops", "organization_id": "org_cloud_ops", "slug": "cloud-ops"},
    {
        "id": "provider_far_mirror",
        "organization_id": "org_far_mirror",
        "slug": "far-mirror",
    },
]


def _service(
    *,
    service_id: str,
    name: str,
    category: str,
    provider_id: str,
    description: str,
    avatar_key: str,
    price: float,
    average_minutes: int,
    revisions: int,
    rating: float,
    orders: int,
    on_time_rate: int,
    response_minutes: int,
    delivery_format: str,
    scope: list[str],
    exclusions: list[str],
    deliverable: tuple[str, str, str],
    process: list[tuple[str, str]],
    acceptance: list[str],
    version: str,
    released_at: str,
    summary: str,
) -> dict[str, Any]:
    return {
        "id": service_id,
        "slug": service_id,
        "name": name,
        "category": category,
        "provider_id": provider_id,
        "description": description,
        "avatar_key": avatar_key,
        "price": price,
        "price_unit": "次",
        "average_minutes": average_minutes,
        "included_revisions": revisions,
        "rating": rating,
        "completed_orders": orders,
        "on_time_rate": on_time_rate,
        "response_minutes": response_minutes,
        "delivery_format": delivery_format,
        "service_scope": scope,
        "exclusions": exclusions,
        "deliverables": [
            {"name": deliverable[0], "format": deliverable[1], "size": deliverable[2]}
        ],
        "process": [
            {"title": title, "description": step_description} for title, step_description in process
        ],
        "acceptance_criteria": acceptance,
        "versions": [
            {
                "version": version,
                "released_at": released_at,
                "summary": summary,
                "current": True,
            }
        ],
    }


AI_SERVICES: list[dict[str, Any]] = [
    _service(
        service_id="contract-review",
        name="合同审查专员",
        category="企业合同风控",
        provider_id="provider_legal_planet",
        description="覆盖合同审查、条款风险识别与合规咨询，依据企业合规制度和历史判例输出审查意见。",
        avatar_key="quality",
        price=199,
        average_minutes=25,
        revisions=2,
        rating=4.9,
        orders=568,
        on_time_rate=98,
        response_minutes=8,
        delivery_format="报告",
        scope=[
            "企业各类合同的合规性审查与风险识别",
            "关键条款审查与修改建议",
            "输出可追溯的专业审查报告",
        ],
        exclusions=["合同谈判与签署", "诉讼或仲裁代理", "争议性法律意见出具"],
        deliverable=("合同审查报告.docx", "Microsoft Word", "56KB"),
        process=[
            ("输入材料", "上传合同及背景资料"),
            ("AI执行", "比对条款、法规与企业规则"),
            ("人工复核", "服务方专家复核建议"),
            ("提交交付", "输出审查报告"),
        ],
        acceptance=[
            "报告包含风险识别、依据条款、修改建议与结论。",
            "关键结论可追溯至合同原文位置。",
        ],
        version="v2.4",
        released_at="2026-07-18",
        summary="强化关键条款定位，新增结构化风险清单。",
    ),
    _service(
        service_id="finance-report",
        name="财务报表分析师",
        category="财务分析",
        provider_id="provider_shujian",
        description="分析财务报表、经营指标和异常数据，输出结构化结论并由财务顾问复核。",
        avatar_key="commerce",
        price=299,
        average_minutes=30,
        revisions=2,
        rating=4.8,
        orders=412,
        on_time_rate=96,
        response_minutes=12,
        delivery_format="表格",
        scope=["财务报表结构化分析", "异常数据定位", "经营指标解释"],
        exclusions=["审计意见出具", "税务申报"],
        deliverable=("财务分析报告.xlsx", "Microsoft Excel", "128KB"),
        process=[
            ("上传报表", "提供财务报表和口径说明"),
            ("AI分析", "识别趋势与异常"),
            ("人工复核", "财务顾问确认口径"),
            ("提交报告", "输出分析结论"),
        ],
        acceptance=["结论可追溯到原始报表。", "指标口径与输入资料一致。"],
        version="v1.8",
        released_at="2026-07-12",
        summary="新增现金流异常检测。",
    ),
    _service(
        service_id="recruitment",
        name="招聘方案专家",
        category="人才引擎",
        provider_id="provider_talent_engine",
        description="提供岗位分析、人才画像、招聘渠道规划与面试流程设计，输出完整招聘方案。",
        avatar_key="service",
        price=169,
        average_minutes=28,
        revisions=2,
        rating=4.7,
        orders=389,
        on_time_rate=97,
        response_minutes=10,
        delivery_format="文档",
        scope=["岗位分析", "人才画像", "渠道规划", "面试流程设计"],
        exclusions=["候选人背调", "猎头服务"],
        deliverable=("招聘执行方案.docx", "Microsoft Word", "82KB"),
        process=[
            ("需求输入", "填写岗位与团队信息"),
            ("方案生成", "生成招聘策略"),
            ("人工复核", "招聘顾问校准"),
            ("方案交付", "提交完整方案"),
        ],
        acceptance=["岗位画像字段完整。", "方案包含渠道、流程与评估标准。"],
        version="v1.5",
        released_at="2026-07-08",
        summary="优化岗位胜任力模型。",
    ),
    _service(
        service_id="after-sales",
        name="电商售后客服",
        category="客户服务",
        provider_id="provider_youfu",
        description="处理售前咨询、订单跟踪、退换货申请与投诉处理，熟悉主流电商平台规则。",
        avatar_key="after-sales",
        price=139,
        average_minutes=22,
        revisions=1,
        rating=4.8,
        orders=1246,
        on_time_rate=95,
        response_minutes=4,
        delivery_format="工作流",
        scope=["售后工单处理", "退换货审核", "投诉分类"],
        exclusions=["线下物流操作", "资金直接退款"],
        deliverable=("售后处理记录.xlsx", "Microsoft Excel", "42KB"),
        process=[
            ("接收工单", "同步订单与客户诉求"),
            ("规则判断", "调用平台规则"),
            ("人工确认", "异常情况转人工"),
            ("结果回传", "回传处理记录"),
        ],
        acceptance=["处理结论符合平台规则。", "全流程留痕可追溯。"],
        version="v3.2",
        released_at="2026-07-21",
        summary="新增投诉升级规则。",
    ),
    _service(
        service_id="bid-writer",
        name="投标文件助手",
        category="标兴咨询",
        provider_id="provider_biaoxing",
        description="协助编写投标文件，包含商务标与技术标内容梳理、方案撰写与排版。",
        avatar_key="default",
        price=259,
        average_minutes=35,
        revisions=2,
        rating=4.9,
        orders=327,
        on_time_rate=96,
        response_minutes=14,
        delivery_format="文档",
        scope=["投标要求提取", "内容框架生成", "合规检查"],
        exclusions=["虚假资质制作", "投标代理"],
        deliverable=("投标文件初稿.docx", "Microsoft Word", "1.2MB"),
        process=[
            ("输入招标书", "上传招标文件"),
            ("要点提取", "生成响应矩阵"),
            ("内容编写", "生成投标初稿"),
            ("人工复核", "顾问完成校验"),
        ],
        acceptance=["响应项与招标书逐项对应。", "缺失资料明确标注。"],
        version="v2.1",
        released_at="2026-07-10",
        summary="新增响应矩阵导出。",
    ),
    _service(
        service_id="it-ops",
        name="IT运维工程师",
        category="云维科技",
        provider_id="provider_cloud_ops",
        description="处理账号权限、设备申领、常见故障排查等 IT 服务请求，能按 SOP 分派工单。",
        avatar_key="ops",
        price=199,
        average_minutes=26,
        revisions=1,
        rating=4.7,
        orders=712,
        on_time_rate=98,
        response_minutes=6,
        delivery_format="工作流",
        scope=["账号权限申请", "设备故障排查", "运维工单流转"],
        exclusions=["物理设备维修", "未经授权的系统变更"],
        deliverable=("运维处理报告.pdf", "PDF", "62KB"),
        process=[
            ("接收请求", "识别问题类型"),
            ("执行SOP", "运行标准流程"),
            ("人工接管", "异常转运维人员"),
            ("结果确认", "回传处理结果"),
        ],
        acceptance=["操作符合权限边界。", "关键步骤可审计。"],
        version="v2.0",
        released_at="2026-07-16",
        summary="新增账号解锁流程。",
    ),
]


def _skill(
    *,
    skill_id: str,
    name: str,
    provider_id: str,
    description: str,
    category: str,
    version: str,
    verification: str,
    runtime: str,
    weight: str,
    price: float,
    price_unit: str,
    installs: int,
    rating: float | None,
    icon: str,
    icon_tone: str,
    permission_tags: list[str],
    scenarios: list[str],
    input_name: str,
    input_type: str,
    input_description: str,
    input_example: str,
    output_name: str,
    output_type: str,
    output_description: str,
    output_example: str,
    permission_key: str,
    permission_label: str,
    permission_level: str,
    permission_detail: str,
    network_policy: str,
    retention_policy: str,
    released_at: str,
    summary: str,
) -> dict[str, Any]:
    return {
        "id": skill_id,
        "slug": skill_id,
        "name": name,
        "provider_id": provider_id,
        "description": description,
        "category": category,
        "version": version,
        "verification": verification,
        "runtime": runtime,
        "language": "Python",
        "weight": weight,
        "price": price,
        "price_unit": price_unit,
        "installs": installs,
        "rating": rating,
        "icon": icon,
        "icon_tone": icon_tone,
        "permission_tags": permission_tags,
        "scenarios": scenarios,
        "inputs": [
            {
                "name": input_name,
                "type": input_type,
                "required": True,
                "description": input_description,
                "example": input_example,
            }
        ],
        "outputs": [
            {
                "name": output_name,
                "type": output_type,
                "required": True,
                "description": output_description,
                "example": output_example,
            }
        ],
        "permissions": [
            {
                "key": permission_key,
                "label": permission_label,
                "level": permission_level,
                "detail": permission_detail,
            }
        ],
        "network_policy": network_policy,
        "retention_policy": retention_policy,
        "digest": "pending" if verification == "pending" else "verified",
        "audited_at": None if verification == "pending" else released_at,
        "auditor": "-" if verification == "pending" else "平台安全团队",
        "versions": [
            {
                "version": version,
                "released_at": released_at,
                "summary": summary,
                "current": True,
            }
        ],
    }


SKILLS: list[dict[str, Any]] = [
    _skill(
        skill_id="contract-structure-parser",
        name="合同条款结构化解析",
        provider_id="provider_legal_planet",
        description="识别合同条款并结构化输出要点，支持风险提示与关键条款定位。",
        category="法务",
        version="v2.4.1",
        verification="verified",
        runtime="平台托管",
        weight="轻量",
        price=0.08,
        price_unit="页",
        installs=1268,
        rating=4.8,
        icon="document",
        icon_tone="violet",
        permission_tags=["读本次附件", "写临时目录", "限定网络"],
        scenarios=["合同审查与尽调", "合同要点提取与归档", "合同对比与变更分析"],
        input_name="contract_file",
        input_type="file",
        input_description="PDF/Word 合同文件",
        input_example="采购合同_2026版.pdf",
        output_name="clauses",
        output_type="array<object>",
        output_description="结构化条款与原文位置索引",
        output_example="条款清单、风险提示与解析置信度",
        permission_key="read_attachment",
        permission_label="读取本次任务附件",
        permission_level="allow",
        permission_detail="仅限当前调用关联附件",
        network_policy="无公网访问",
        retention_policy="任务结束后 24 小时删除临时数据",
        released_at="2026-07-18",
        summary="优化条款分类模型，新增解析质量报告。",
    ),
    _skill(
        skill_id="quote-generator",
        name="AI服务报价生成器",
        provider_id="provider_kaigongba",
        description="根据客户需求与历史数据，智能生成专业服务报价单与交付计划。",
        category="交易",
        version="v1.8.0",
        verification="official",
        runtime="平台托管",
        weight="轻量",
        price=0,
        price_unit="次",
        installs=5432,
        rating=4.9,
        icon="robot",
        icon_tone="blue",
        permission_tags=["读本次附件", "写临时目录"],
        scenarios=["需求解析", "报价草稿生成"],
        input_name="requirement",
        input_type="object",
        input_description="结构化需求",
        input_example="需求对象",
        output_name="quote",
        output_type="object",
        output_description="报价草稿",
        output_example="报价与里程碑",
        permission_key="read_order",
        permission_label="读取当前需求",
        permission_level="allow",
        permission_detail="只读当前需求",
        network_policy="无公网访问",
        retention_policy="任务结束后立即清理",
        released_at="2026-07-20",
        summary="新增里程碑报价建议。",
    ),
    _skill(
        skill_id="excel-insight",
        name="Excel经营数据洞察",
        provider_id="provider_shujian",
        description="从 Excel 经营数据中洞察趋势、异常与关键指标，输出可视化总结与建议。",
        category="数据",
        version="v1.3.5",
        verification="verified",
        runtime="远程 API",
        weight="标准",
        price=0.12,
        price_unit="千行",
        installs=3112,
        rating=4.7,
        icon="sheet",
        icon_tone="green",
        permission_tags=["读本次附件", "不写入持久化", "限定网络"],
        scenarios=["经营分析", "异常识别"],
        input_name="workbook",
        input_type="file",
        input_description="Excel 文件",
        input_example="经营数据.xlsx",
        output_name="insights",
        output_type="object",
        output_description="洞察报告",
        output_example="指标、异常与结论",
        permission_key="limited_network",
        permission_label="访问限定网络",
        permission_level="review",
        permission_detail="仅允许已备案域名",
        network_policy="仅允许白名单域名",
        retention_policy="不写入持久化存储",
        released_at="2026-07-12",
        summary="优化异常检测。",
    ),
    _skill(
        skill_id="public-search",
        name="公开信息检索与取证",
        provider_id="provider_far_mirror",
        description="面向合规场景的公开信息检索、线索归集与证据链整理，生成取证报告。",
        category="研究",
        version="v0.9.3",
        verification="pending",
        runtime="远程 API",
        weight="标准",
        price=0.15,
        price_unit="次",
        installs=621,
        rating=None,
        icon="search",
        icon_tone="orange",
        permission_tags=["读公开数据", "不写入持久化", "限定网络"],
        scenarios=["公开信息检索"],
        input_name="query",
        input_type="string",
        input_description="检索目标",
        input_example="企业名称",
        output_name="evidence",
        output_type="object",
        output_description="证据链报告",
        output_example="来源、摘要与证据索引",
        permission_key="public_network",
        permission_label="访问公开网络",
        permission_level="review",
        permission_detail="需要安全验证",
        network_policy="待安全验证",
        retention_policy="不写入持久化存储",
        released_at="2026-07-02",
        summary="公开测试版本。",
    ),
    _skill(
        skill_id="job-description",
        name="招聘JD优化",
        provider_id="provider_talent_engine",
        description="优化职位描述，提升吸引力与匹配度，输出多版本 JD 与核心要求清单。",
        category="招聘",
        version="v1.2.0",
        verification="verified",
        runtime="平台托管",
        weight="轻量",
        price=0.06,
        price_unit="篇",
        installs=2845,
        rating=4.6,
        icon="people",
        icon_tone="violet",
        permission_tags=["读本次内容", "写临时目录"],
        scenarios=["JD 优化"],
        input_name="jd",
        input_type="string",
        input_description="职位描述",
        input_example="原始 JD",
        output_name="optimized_jd",
        output_type="string",
        output_description="优化结果",
        output_example="多个版本的优化 JD",
        permission_key="read_text",
        permission_label="读取本次输入",
        permission_level="allow",
        permission_detail="仅限本次内容",
        network_policy="无公网访问",
        retention_policy="任务结束后立即清理",
        released_at="2026-07-05",
        summary="新增多版本输出。",
    ),
    _skill(
        skill_id="ticket-classifier",
        name="工单分类器",
        provider_id="provider_cloud_ops",
        description="自动识别工单类型与优先级并分配处理人，支持多维标签与路由策略。",
        category="运维",
        version="v2.0.1",
        verification="verified",
        runtime="平台托管",
        weight="轻量",
        price=0.04,
        price_unit="单",
        installs=4128,
        rating=4.8,
        icon="tag",
        icon_tone="blue",
        permission_tags=["读本次内容", "不写入持久化"],
        scenarios=["工单路由"],
        input_name="ticket",
        input_type="object",
        input_description="工单内容",
        input_example="工单对象",
        output_name="classification",
        output_type="object",
        output_description="分类结果",
        output_example="标签、优先级与处理人",
        permission_key="read_ticket",
        permission_label="读取当前工单",
        permission_level="allow",
        permission_detail="仅限本次工单",
        network_policy="无公网访问",
        retention_policy="不写入持久化存储",
        released_at="2026-07-15",
        summary="新增多维标签。",
    ),
]


SUBSCRIBED_SERVICE_IDS = {"contract-review", "finance-report", "after-sales"}
