server {
    listen 80;
    listen [::]:80;
    server_name app.kaigongba.net;

    root /opt/kaigongba-app/current/frontend;

    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
