import avatarAfterSales from '@/assets/staffdeck/staffdeck-avatar-after-sales.png';
import avatarCommerce from '@/assets/staffdeck/staffdeck-avatar-commerce.png';
import avatarDefault from '@/assets/staffdeck/staffdeck-avatar-default.png';
import avatarOps from '@/assets/staffdeck/staffdeck-avatar-ops.png';
import avatarQuality from '@/assets/staffdeck/staffdeck-avatar-quality.png';
import avatarService from '@/assets/staffdeck/staffdeck-avatar-service.png';
import type { AiService, MarketplaceSkill } from './types';

const contractScope = [
  '企业各类合同的合规性审查与风险识别',
  '关键条款（权利义务、违约责任、保密、知识产权等）审查',
  '提供审查意见与修改建议，降低合同法律风险',
  '基于企业制度和历史判例，输出专业审查报告',
];
const contractExclusions = [
  '合同起草、谈判与签署',
  '争议性法律意见出具',
  '诉讼代理或仲裁代理服务',
  '超出本服务范围的专项法律服务',
];

export const aiServiceFixtures: AiService[] = [
  {
    id: 'contract-review',
    name: '合同审查专员',
    category: '企业合同风控',
    provider: '法务星球工作室',
    providerSlug: 'legal-planet',
    providerVerified: true,
    avatar: avatarQuality,
    description: '覆盖合同审查、条款风险识别与合规咨询，依据企业合规制度和历史判例输出审查意见。',
    verified: true,
    online: true,
    price: 199,
    priceUnit: '次',
    averageMinutes: 25,
    includedRevisions: 2,
    rating: 4.9,
    completedOrders: 568,
    onTimeRate: 98,
    responseMinutes: 8,
    subscribed: true,
    deliveryFormat: '报告',
    serviceScope: contractScope,
    exclusions: contractExclusions,
    deliverables: [
      { name: '合同审查报告.docx', format: 'Microsoft Word', size: '56KB' },
      { name: '风险清单与建议.pdf', format: 'PDF', size: '182KB' },
      { name: '条款修改对照表.xlsx', format: 'Microsoft Excel', size: '98KB' },
    ],
    process: [
      { title: '输入材料', description: '上传合同及背景资料，填写需求说明' },
      { title: 'AI执行', description: '比对条款、法规与企业规则' },
      { title: '人工复核', description: '服务方专家复核并完善建议' },
      { title: '提交交付', description: '输出审查报告与修改建议' },
    ],
    acceptanceCriteria: [
      '审查报告包含风险识别、依据条款、建议修改内容与结论。',
      '识别的关键风险条款不少于平台标准样例评估的 80%。',
      '对采购方提出的问题在约定时效内给予清晰答复。',
      '文档格式规范、内容专业，可直接用于内部决策参考。',
    ],
    versions: [
      { version: 'v2.4', releasedAt: '2026-07-18', current: true, summary: '强化关键条款定位，新增结构化风险清单。' },
      { version: 'v2.3', releasedAt: '2026-05-22', summary: '优化长合同解析与原文位置索引。' },
    ],
  },
  {
    id: 'finance-report',
    name: '财务报表分析师',
    category: '财务分析',
    provider: '数见智能',
    providerSlug: 'shujian',
    providerVerified: true,
    avatar: avatarCommerce,
    description: '熟悉公司报销、差旅、预算与发票全流程，能解答报销政策，核对单据合规性。',
    verified: true,
    online: true,
    price: 299,
    priceUnit: '次',
    averageMinutes: 30,
    includedRevisions: 2,
    rating: 4.8,
    completedOrders: 412,
    onTimeRate: 96,
    responseMinutes: 12,
    subscribed: true,
    deliveryFormat: '表格',
    serviceScope: ['财务报表结构化分析', '异常数据定位', '经营指标解释'],
    exclusions: ['审计意见出具', '税务申报'],
    deliverables: [{ name: '财务分析报告.xlsx', format: 'Microsoft Excel', size: '128KB' }],
    process: [
      { title: '上传报表', description: '提供财务报表和口径说明' },
      { title: 'AI分析', description: '识别趋势与异常' },
      { title: '人工复核', description: '财务顾问确认口径' },
      { title: '提交报告', description: '输出分析结论' },
    ],
    acceptanceCriteria: ['结论可追溯到原始报表。', '指标口径与输入资料一致。'],
    versions: [{ version: 'v1.8', releasedAt: '2026-07-12', current: true, summary: '新增现金流异常检测。' }],
  },
  {
    id: 'recruitment',
    name: '招聘方案专家',
    category: '人才引擎',
    provider: '人才引擎',
    providerSlug: 'talent-engine',
    providerVerified: true,
    avatar: avatarService,
    description: '提供岗位分析、人才画像、招聘渠道规划与面试流程设计，输出完整招聘方案。',
    verified: true,
    online: true,
    price: 169,
    priceUnit: '次',
    averageMinutes: 28,
    includedRevisions: 2,
    rating: 4.7,
    completedOrders: 389,
    onTimeRate: 97,
    responseMinutes: 10,
    deliveryFormat: '文档',
    serviceScope: ['岗位分析', '人才画像', '渠道规划', '面试流程设计'],
    exclusions: ['候选人背调', '猎头服务'],
    deliverables: [{ name: '招聘执行方案.docx', format: 'Microsoft Word', size: '82KB' }],
    process: [
      { title: '需求输入', description: '填写岗位与团队信息' },
      { title: '方案生成', description: '生成招聘策略' },
      { title: '人工复核', description: '招聘顾问校准' },
      { title: '方案交付', description: '提交完整方案' },
    ],
    acceptanceCriteria: ['岗位画像字段完整。', '方案包含渠道、流程与评估标准。'],
    versions: [{ version: 'v1.5', releasedAt: '2026-07-08', current: true, summary: '优化岗位胜任力模型。' }],
  },
  {
    id: 'after-sales',
    name: '电商售后客服',
    category: '客户服务',
    provider: '优服智能',
    providerSlug: 'youfu',
    providerVerified: true,
    avatar: avatarAfterSales,
    description: '处理售前咨询、订单跟踪、退换货申请与投诉处理，熟悉主流电商平台规则。',
    verified: true,
    online: true,
    price: 139,
    priceUnit: '次',
    averageMinutes: 22,
    includedRevisions: 1,
    rating: 4.8,
    completedOrders: 1246,
    onTimeRate: 95,
    responseMinutes: 4,
    subscribed: true,
    mine: true,
    deliveryFormat: '工作流',
    serviceScope: ['售后工单处理', '退换货审核', '投诉分类'],
    exclusions: ['线下物流操作', '资金直接退款'],
    deliverables: [{ name: '售后处理记录.xlsx', format: 'Microsoft Excel', size: '42KB' }],
    process: [
      { title: '接收工单', description: '同步订单与客户诉求' },
      { title: '规则判断', description: '调用平台规则' },
      { title: '人工确认', description: '异常情况转人工' },
      { title: '结果回传', description: '回传处理记录' },
    ],
    acceptanceCriteria: ['处理结论符合平台规则。', '全流程留痕可追溯。'],
    versions: [{ version: 'v3.2', releasedAt: '2026-07-21', current: true, summary: '新增投诉升级规则。' }],
  },
  {
    id: 'bid-writer',
    name: '投标文件助手',
    category: '标兴咨询',
    provider: '标兴咨询',
    providerSlug: 'biaoxing',
    providerVerified: true,
    avatar: avatarDefault,
    description: '协助编写投标文件，包含商务标与技术标内容梳理、方案撰写与排版。',
    verified: true,
    online: true,
    price: 259,
    priceUnit: '次',
    averageMinutes: 35,
    includedRevisions: 2,
    rating: 4.9,
    completedOrders: 327,
    onTimeRate: 96,
    responseMinutes: 14,
    deliveryFormat: '文档',
    serviceScope: ['投标要求提取', '内容框架生成', '合规检查'],
    exclusions: ['虚假资质制作', '投标代理'],
    deliverables: [{ name: '投标文件初稿.docx', format: 'Microsoft Word', size: '1.2MB' }],
    process: [
      { title: '输入招标书', description: '上传招标文件' },
      { title: '要点提取', description: '生成响应矩阵' },
      { title: '内容编写', description: '生成投标初稿' },
      { title: '人工复核', description: '顾问完成校验' },
    ],
    acceptanceCriteria: ['响应项与招标书逐项对应。', '缺失资料明确标注。'],
    versions: [{ version: 'v2.1', releasedAt: '2026-07-10', current: true, summary: '新增响应矩阵导出。' }],
  },
  {
    id: 'it-ops',
    name: 'IT运维工程师',
    category: '云维科技',
    provider: '云维科技',
    providerSlug: 'cloud-ops',
    providerVerified: true,
    avatar: avatarOps,
    description: '处理账号权限、设备申领、常见故障排查等 IT 服务请求，能按 SOP 分派工单。',
    verified: true,
    online: true,
    price: 199,
    priceUnit: '次',
    averageMinutes: 26,
    includedRevisions: 1,
    rating: 4.7,
    completedOrders: 712,
    onTimeRate: 98,
    responseMinutes: 6,
    deliveryFormat: '工作流',
    serviceScope: ['账号权限申请', '设备故障排查', '运维工单流转'],
    exclusions: ['物理设备维修', '未经授权的系统变更'],
    deliverables: [{ name: '运维处理报告.pdf', format: 'PDF', size: '62KB' }],
    process: [
      { title: '接收请求', description: '识别问题类型' },
      { title: '执行SOP', description: '运行标准流程' },
      { title: '人工接管', description: '异常转运维人员' },
      { title: '结果确认', description: '回传处理结果' },
    ],
    acceptanceCriteria: ['操作符合权限边界。', '关键步骤可审计。'],
    versions: [{ version: 'v2.0', releasedAt: '2026-07-16', current: true, summary: '新增账号解锁流程。' }],
  },
];

export const skillFixtures: MarketplaceSkill[] = [
  {
    id: 'contract-structure-parser',
    name: '合同条款结构化解析',
    provider: '法务星球工作室',
    providerSlug: 'legal-planet',
    description: '识别合同条款并结构化输出要点，支持风险提示与关键条款定位。',
    category: '法务',
    version: 'v2.4.1',
    verification: 'verified',
    runtime: '平台托管',
    language: 'Python',
    weight: '轻量',
    price: 0.08,
    priceUnit: '页',
    installs: 1268,
    rating: 4.8,
    icon: 'document',
    iconTone: 'violet',
    permissionTags: ['读本次附件', '写临时目录', '限定网络'],
    installed: true,
    scenarios: ['合同审查与尽调', '合同要点提取与归档', '合同对比与变更分析', '法律合规检查'],
    inputs: [
      { name: 'contract_file', type: 'file', required: true, description: 'PDF/Word 合同文件', example: '采购合同_2026版.pdf' },
      { name: 'contract_type', type: 'string', required: false, description: '合同类型', example: '采购合同' },
    ],
    outputs: [
      { name: 'clauses', type: 'array<object>', required: true, description: '条款清单 JSON', example: '结构化条款与要点' },
      { name: 'key_positions', type: 'array<object>', required: true, description: '原文位置索引', example: '条款页码与位置' },
      { name: 'analysis_report', type: 'object', required: true, description: '解析质量报告', example: '风险提示与解析置信度' },
    ],
    permissions: [
      { key: 'read_attachment', label: '读取本次任务附件', level: 'allow', detail: '仅限当前调用关联附件' },
      { key: 'write_temp', label: '写入任务临时目录', level: 'allow', detail: '任务结束后自动清理' },
      { key: 'read_kb', label: '读取企业知识库', level: 'deny', detail: '默认禁止' },
      { key: 'network', label: '访问公网', level: 'deny', detail: '无公网访问' },
      { key: 'secrets', label: '读取密钥', level: 'deny', detail: '不允许访问企业密钥' },
    ],
    networkPolicy: '无公网访问',
    retentionPolicy: '任务结束后 24 小时删除临时数据',
    digest: 'verified',
    auditedAt: '2026-07-10',
    auditor: '平台安全团队',
    versions: [
      { version: 'v2.4.1', releasedAt: '2026-07-18', current: true, summary: '优化条款分类模型，新增解析质量报告。' },
      { version: 'v2.3.0', releasedAt: '2026-05-22', summary: '新增原文位置索引，提升长文档解析稳定性。' },
    ],
  },
  {
    id: 'quote-generator',
    name: 'AI服务报价生成器',
    provider: '开工吧官方',
    providerSlug: 'kaigongba',
    description: '根据客户需求与历史数据，智能生成专业服务报价单与交付计划。',
    category: '交易',
    version: 'v1.8.0',
    verification: 'official',
    runtime: '平台托管',
    language: 'Python',
    weight: '轻量',
    price: 0,
    priceUnit: '次',
    installs: 5432,
    rating: 4.9,
    icon: 'robot',
    iconTone: 'blue',
    permissionTags: ['读本次附件', '写临时目录'],
    installed: true,
    scenarios: ['需求解析', '报价草稿生成'],
    inputs: [{ name: 'requirement', type: 'object', required: true, description: '结构化需求', example: '需求对象' }],
    outputs: [{ name: 'quote', type: 'object', required: true, description: '报价草稿', example: '报价与里程碑' }],
    permissions: [{ key: 'read_order', label: '读取当前需求', level: 'allow', detail: '只读当前需求' }],
    networkPolicy: '无公网访问',
    retentionPolicy: '任务结束后立即清理',
    digest: 'verified',
    auditedAt: '2026-07-20',
    auditor: '平台安全团队',
    versions: [{ version: 'v1.8.0', releasedAt: '2026-07-20', current: true, summary: '新增里程碑报价建议。' }],
  },
  {
    id: 'excel-insight',
    name: 'Excel经营数据洞察',
    provider: '数见智能',
    providerSlug: 'shujian',
    description: '从 Excel 经营数据中洞察趋势、异常与关键指标，输出可视化总结与建议。',
    category: '数据',
    version: 'v1.3.5',
    verification: 'verified',
    runtime: '远程 API',
    language: 'Python',
    weight: '标准',
    price: 0.12,
    priceUnit: '千行',
    installs: 3112,
    rating: 4.7,
    icon: 'sheet',
    iconTone: 'green',
    permissionTags: ['读本次附件', '不写入持久化', '限定网络'],
    scenarios: ['经营分析', '异常识别'],
    inputs: [{ name: 'workbook', type: 'file', required: true, description: 'Excel 文件', example: '经营数据.xlsx' }],
    outputs: [{ name: 'insights', type: 'object', required: true, description: '洞察报告', example: '指标与结论' }],
    permissions: [{ key: 'limited_network', label: '访问限定网络', level: 'review', detail: '仅允许已备案域名' }],
    networkPolicy: '仅允许白名单域名',
    retentionPolicy: '不写入持久化存储',
    digest: 'verified',
    auditedAt: '2026-07-12',
    auditor: '平台安全团队',
    versions: [{ version: 'v1.3.5', releasedAt: '2026-07-12', current: true, summary: '优化异常检测。' }],
  },
  {
    id: 'public-search',
    name: '公开信息检索与取证',
    provider: '远镜研究社',
    providerSlug: 'far-mirror',
    description: '面向合规场景的公开信息检索、线索归集与证据链整理，生成取证报告。',
    category: '研究',
    version: 'v0.9.3',
    verification: 'pending',
    runtime: '远程 API',
    language: 'Python',
    weight: '标准',
    price: 0.15,
    priceUnit: '次',
    installs: 621,
    rating: null,
    icon: 'search',
    iconTone: 'orange',
    permissionTags: ['读公开数据', '不写入持久化', '限定网络'],
    scenarios: ['公开信息检索'],
    inputs: [{ name: 'query', type: 'string', required: true, description: '检索目标', example: '企业名称' }],
    outputs: [{ name: 'evidence', type: 'object', required: true, description: '证据链报告', example: '来源与摘要' }],
    permissions: [{ key: 'public_network', label: '访问公开网络', level: 'review', detail: '需要安全验证' }],
    networkPolicy: '待安全验证',
    retentionPolicy: '不写入持久化存储',
    digest: 'pending',
    auditedAt: '-',
    auditor: '-',
    versions: [{ version: 'v0.9.3', releasedAt: '2026-07-02', current: true, summary: '公开测试版本。' }],
  },
  {
    id: 'job-description',
    name: '招聘JD优化',
    provider: '人才引擎',
    providerSlug: 'talent-engine',
    description: '优化职位描述，提升吸引力与匹配度，输出多版本 JD 与核心要求清单。',
    category: '招聘',
    version: 'v1.2.0',
    verification: 'verified',
    runtime: '平台托管',
    language: 'Python',
    weight: '轻量',
    price: 0.06,
    priceUnit: '篇',
    installs: 2845,
    rating: 4.6,
    icon: 'people',
    iconTone: 'violet',
    permissionTags: ['读本次内容', '写临时目录'],
    scenarios: ['JD 优化'],
    inputs: [{ name: 'jd', type: 'string', required: true, description: '职位描述', example: '原始 JD' }],
    outputs: [{ name: 'optimized_jd', type: 'string', required: true, description: '优化结果', example: '优化 JD' }],
    permissions: [{ key: 'read_text', label: '读取本次输入', level: 'allow', detail: '仅限本次内容' }],
    networkPolicy: '无公网访问',
    retentionPolicy: '任务结束后立即清理',
    digest: 'verified',
    auditedAt: '2026-07-05',
    auditor: '平台安全团队',
    versions: [{ version: 'v1.2.0', releasedAt: '2026-07-05', current: true, summary: '新增多版本输出。' }],
  },
  {
    id: 'ticket-classifier',
    name: '工单分类器',
    provider: '云维科技',
    providerSlug: 'cloud-ops',
    description: '自动识别工单类型与优先级并分配处理人，支持多维标签与路由策略。',
    category: '运维',
    version: 'v2.0.1',
    verification: 'verified',
    runtime: '平台托管',
    language: 'Python',
    weight: '轻量',
    price: 0.04,
    priceUnit: '单',
    installs: 4128,
    rating: 4.8,
    icon: 'tag',
    iconTone: 'blue',
    permissionTags: ['读本次内容', '不写入持久化'],
    mine: true,
    scenarios: ['工单路由'],
    inputs: [{ name: 'ticket', type: 'object', required: true, description: '工单内容', example: '工单对象' }],
    outputs: [{ name: 'classification', type: 'object', required: true, description: '分类结果', example: '标签与处理人' }],
    permissions: [{ key: 'read_ticket', label: '读取当前工单', level: 'allow', detail: '仅限本次工单' }],
    networkPolicy: '无公网访问',
    retentionPolicy: '不写入持久化存储',
    digest: 'verified',
    auditedAt: '2026-07-15',
    auditor: '平台安全团队',
    versions: [{ version: 'v2.0.1', releasedAt: '2026-07-15', current: true, summary: '新增多维标签。' }],
  },
];
